### ISSUE TITLE
Link to applied migration show only there are no migrations

### ISSUE THREAD

**Issue by asparkam** [Firstborn/Craft-CMS-Migration-Manager#20]
There are no link to applied migrations list if at least one migration is existing. But by the link /migrationmanager/applied it is available

![image](https://user-images.githubusercontent.com/30487905/35040023-4b8aecd2-fbb2-11e7-8cc0-a92c04991292.png)
![image](https://user-images.githubusercontent.com/30487905/35040043-5b692af6-fbb2-11e7-973e-ae7d39073d4b.png)

**Comment by fb-derrick-grigg** [comment]
This is functioning correctly. When you generate a migration, it is automatically added to the applied list (since the field/section/etc already exists). In this case the pending migrations list is 0 and the applied migrations list is 1. When that migration appears new (ie via a git pull) in the destination site the pending migrations list is 1 and the applied migrations list is 0 until a migration successfully runs.

**Comment by asparkam** [comment]
@fb-derrick-grigg in other words, I can not look at the list of old migrations, while I have at least one migration?

**Comment by fb-derrick-grigg** [comment]
Ah, I see the issue. No you should always be able to see the applied migrations if any exist. Try the latest.

**Comment by asparkam** [comment]
@fb-derrick-grigg sorry, for my bad English:)
